[package]
name = "bn-objc-extras"
version = "0.1.0"
edition = "2024"

[dependencies]
binaryninja = { git = "https://github.com/Vector35/binaryninja-api.git", branch = "dev" }
log = "0.4"
itertools = "0.13"
bn-bdash-extras = { git = "https://github.com/bdash/bn-bdash-extras", branch = "dev" }
bstr = "1.12.0"

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"
build-override.debug = true

[profile.release]
panic = "abort"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_sign_loss = "allow"
items_after_statements = "allow"
too_many_lines = "allow"

